spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"