spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payment-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/payments/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"