server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payments/**
            - Method=POST
          filters:
            - StripPrefix=0

        - id: payment-service-all
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payments/**
            - Method=GET
          filters:
            - StripPrefix=0
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG